site_name: Instagram Recipe Explorer
theme:
  name: material
  features:    
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky



edit_uri: blob/main/docs
repo_url: https://github.com/lucharo/recipes
remote_branch: gh-pages

nav: 
  - Home: index.md

extra_css:
  - style.css

plugins:
  - search

markdown_extensions: 
  - attr_list
  - md_in_html