site_name: IG Recipe Explorer
theme:
  name: material
  features:
    - content.action.view
  icon:
    edit: material/pencil 
    view: material/eye

edit_uri: blob/main/docs
repo_url: https://github.com/lucharo/recipes
remote_branch: gh-pages

extra_css:
  - style.css

plugins:
  - search

markdown_extensions: 
  - attr_list
  - md_in_html